* Prompt
  Write a brief statement of purpose describing reason(s) for pursuing graduate or post baccalaureate study. Include any additional information concerning your preparation that is pertinent to the objective specified
* Answer
  Computer Science has always been a main theme throughout my undergraduate study. Back in community college, classes such as programming in C++ and Data Structure open the door to programming. After transfer to UCLA as a Electrical Engineering major, I am exposed to more advanced CS classes such as Logic Design of Digital Systems and Introduction to Computer Organization. As my interest in Computer Science grows, my focus of study was steered towards Computer Science. In particular, I chose my technical breadth area in CS and took classes such as Introduction to Machine Learning which really open my eyes on what Computer Science can do. As my undergraduate program is coming to an end, I want to pursue graduate study to further my skill and knowledge in Artificial Intelligence and Web Development. I believe the graduate programme in CSU is a good fit for me and my interest in these areas of studies.  

  I have benefited vastly from the breadth of UCLA's undergraduate syllabus and gained a comprehensive exposure to many core areas of the field, such as Signal Processing, Semiconductor Devices, Circuit Designing, etc. Moreover, the variety of equivalent classes in the CS and EE department also give me a strong conceptual understanding in the field of Computer Science, such as programming in C, Computer Organization, and Machine Learnings. In particular, what interest me the most is Artificial Intelligence. I found it incredible that simple ideas such as Decision Trees, Nearest Neighbor, and regressions are able to solve practical problems in real life. I was fascinated by the more advanced algorithm such as Kernelization, Support Vector Machine, Adaboost, etc. and was astonished by the magical ways they work. Moreover, the excitement by reading the chess AI AlphaZero paper by the Google Deep Mind team further confirms my ambition in Artificial Intelligence. I think the Master programme in CSU will give me great opportunities in the AI field, allowing me to excel my skill sets, and be part of this future life-changing trend.

  The constant exposure of Computer Science allows me to expand in the field of Web Developing. Being able to set up a website of my own has been my dream since elementary school. In the summer of 2017, I finally put my dream into action. By web-research and self-learning, I was able to set up a virtual host in Digital Ocean, bought my domain in GoDaddy, and configure Nginx through ssh. In the making of my own server, I learned essential languages such as HTML, CSS, and JavaScript. Moreover, to run my own nodejs applications, I explored the possibilities of the MEAN stack and the backed non-SQL database system provided by Mongodb. Although it is far from completion, the environment I set up and programming knowledges I learned is a major step forward to achieving my dream. In the pursuit of my master degree, one main objective is to fulfill this dream of mine -- to learn more about Web Development. Knowing that Cyber security is an indispensable part in Web Development, related classes offered in CSU such as Cryptography and Information Security will definitely help me reach my goal.

  I am doing a year-long project with IEEE right now with three other teammates. Our goal is to build a wireless quadcopter by the end of Spring. In the first quarter, we have learned how to communicate wirelessly using RF modules through SPI communication protocol, sensor fusion with Accelerometer and Gyroscope to get orientation, and motor control. Although the project EE based, there are lots of actual programming implementation for these electronic components to work properly. Being the project leader, I learned how to overcome practical difficulties in the implantation of an engineering project -- rereading the datasheet, debugging the code implementation and testing proper function of components. Moreover, I learned how crucial collaboration is in the course of Engineering project. I also learned to take both praise and criticism constructively. This was a very instructive and gratifying experience which I feel will have me in good shape in my career as an Engineer.

  I would like to say in conclusion that your esteemed college with its high-tech facilities would help me best with my academic pursuits and is a major step towards achieving my objectives. I would be grateful if I am given the opportunity to pursue my graduate study at your world-renowned institution.
