#+OPTION: \n:t
* Prompt
  Write a brief statement of purpose describing reason(s) for pursuing graduate or post baccalaureate study. Include any additional information concerning your preparation that is pertinent to the objective specified
* Answer
  My primary interest in computer engineering are Robotics, Machine Learning, and Web Development. I have benefited vastly from the breadth of UCLA's undergraduate syllabus and gained a comprehensive exposure to many core areas in these fields. \\\\
  My interest in Robotics was first kindled in my design course "Design of Robotic Systems". I remember the first project we did on Kinematics analysis on a chair. It was such a fun experience working with teammates figuring out the DH parameters with our right hand spinning around. I also implemented code for forward and inverse Kinematics for the rigid system in Matlab. \\\\
  The project-based nature of this course really drives me to put my heart and soul in. I did one of the most challenging projects in my undergraduate study -- state estimation and motion planning for a two-wheel car. I derived the state-evolution as well as the state-to-measurement formulas, linearized them, and pass them through a Kalman filter. Coded in Matlab, we were able to control the movement of the physical car while simultaneously estimate the state of the car and map the real time estimated position on a plot in Matlab. As part of the project, we then design our parallel parking algorithm based on this state estimation. The algorithm consists of finding the milestones given inputs, and then split the whole parking procedures in a few stages. In each stage, the car aim to iteratively get closer to that milestone before moving on to the next stage. This project taught me a great deal about what the main tasks of Robotics are and useful tools to solve them. \\\\
  I've always been fascinated by how machine learns and any artificial intelligence related topics. Doing a project in my deep learning class definitely open my eye to the field. The goal was to build a model to decode EEG data into 4 classes of motor signals. Taking inspiration from research on EEG signals, I implemented varieties of CNN/RNN architectures, such as a few convolution layers specifically designed to extract features from raw EEG data before passing it through a the LSTM layer. After hours of testing and tuning hyperparameters, we were able to achieve 72% validation accuracy with a pure CNN architecture. This course has really build me a strong understanding of modern state-of-the-art machine learning models and opens up countless possibilities for projects application. \\\\
  My web development project was took place in summer 2017. By web-research and self-teaching, I was able to set up a virtual host in Digital Ocean hosting my domain, with my own nodejs application running on it 24/7. This project not only gives me a thorough understanding in the making of website and the Internet, but also familiarize myself with the tools for web development, including the MEAN stack, backend with user authorization and authentication using Passport.js, and frontend with JQuery and Bootstrap. \\\\
  I plan to continue my study of Robotics, Artificial Intelligence, and Web Development in graduate school. I feel that your esteemed college with its high-tech facilities would help me best with my academic pursuits and is a major step towards achieving my goals. I would be grateful if I am given the opportunity to pursue my graduate study at your world-renowned institution.


